# Generated by Django 5.0.6 on 2026-05-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_level',
            field=models.CharField(choices=[('TRUSTED', 'Trusted (auto-entry, no biometric)'), ('NORMAL', 'Normal (biometric required)'), ('SUSPICIOUS', 'Suspicious (always verify + alert)')], default='NORMAL', help_text='How strict the gate should be with this driver.', max_length=12),
        ),
    ]
