# Generated by Django 5.0.6 on 2026-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_trust_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=60, help_text='0-100 trust score. Updated automatically on every access event.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_level',
            field=models.CharField(choices=[('TRUSTED', 'Trusted (auto-entry, no biometric)'), ('NORMAL', 'Normal (biometric required)'), ('SUSPICIOUS', 'Suspicious (always verify + alert)')], default='NORMAL', help_text='Auto-derived from trust_score; admin can override.', max_length=12),
        ),
    ]
