# Generated by Django 5.0.6 on 2026-05-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_activity_at_user_trust_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic_doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/cnic/'),
        ),
        migrations.AddField(
            model_name='user',
            name='documents_verified',
            field=models.BooleanField(default=False, help_text='Admin has reviewed driving licence + CNIC and confirmed identity.'),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license_doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/license/'),
        ),
    ]
