# Generated by Django 5.0.6 on 2026-05-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('OWNER', 'Owner'), ('DRIVER', 'Driver'), ('BOTH', 'Owner & Driver')], default='DRIVER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'vehicle')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='users',
            field=models.ManyToManyField(related_name='vehicles', through='vehicles.UserVehicle', to=settings.AUTH_USER_MODEL),
        ),
    ]
