# Generated by Django 5.0.6 on 2026-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_owner_uservehicle_vehicle_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='block_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('UNDER_REVIEW', 'Under review')], default='ACTIVE', help_text='Operational state — BLOCKED rejects entry, UNDER_REVIEW pends admin approval.', max_length=14),
        ),
    ]
