# Generated by Django 5.0.6 on 2026-05-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_block_reason_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/vehicle/'),
        ),
    ]
