# Generated by Django 5.0.6 on 2026-05-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('vehicles', '0002_remove_vehicle_owner_uservehicle_vehicle_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PARKED', 'Parked'), ('EXITED', 'Exited')], default='PARKED', max_length=10)),
                ('entry_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_session', to='access.accesslog')),
                ('entry_user', models.ForeignKey(blank=True, help_text='Driver verified at entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_sessions', to=settings.AUTH_USER_MODEL)),
                ('exit_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_session', to='access.accesslog')),
                ('exit_user', models.ForeignKey(blank=True, help_text='Driver verified at exit (may differ from entry_user).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-entry_time',),
                'indexes': [models.Index(fields=['status'], name='parking_par_status_db8e1f_idx'), models.Index(fields=['-entry_time'], name='parking_par_entry_t_1d4168_idx')],
            },
        ),
    ]
