# Generated by Django 5.0.6 on 2026-05-07 17:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusted_threshold', models.IntegerField(default=80, help_text='Score >= this is TRUSTED.')),
                ('normal_threshold', models.IntegerField(default=50, help_text='Score >= this is NORMAL, otherwise SUSPICIOUS.')),
                ('peak_start', models.TimeField(default=datetime.time(18, 0))),
                ('peak_end', models.TimeField(default=datetime.time(23, 0))),
                ('peak_enabled', models.BooleanField(default=True)),
                ('autonomous_mode', models.BooleanField(default=True, help_text='If False, every access requires explicit verification.')),
                ('force_biometric_during_peak', models.BooleanField(default=True)),
                ('auto_entry_for_trusted', models.BooleanField(default=True, help_text='If False, even TRUSTED users must verify biometric.')),
                ('ocr_min_confidence_normal', models.CharField(default='medium', max_length=10)),
                ('ocr_min_confidence_peak', models.CharField(default='high', max_length=10)),
                ('risk_low_max', models.IntegerField(default=30, help_text='Risk <= this means LOW risk, auto-grant possible.')),
                ('risk_medium_max', models.IntegerField(default=70, help_text='Risk <= this means MEDIUM (require biometric); above is HIGH (deny/escalate).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy configuration',
                'verbose_name_plural': 'Policy configuration',
            },
        ),
    ]
