# Generated by Django 5.0.6 on 2026-05-13 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_incident'),
        ('parking', '0002_policyconfig'),
        ('vehicles', '0004_vehicle_registration_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PARKED')), fields=('vehicle',), name='unique_active_session_per_vehicle'),
        ),
    ]
