# Generated by Django 5.0.6 on 2026-05-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_remove_vehicle_owner_uservehicle_vehicle_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], default='ENTRY', max_length=10)),
                ('plate_detected', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('DENIED', 'Denied'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('plate_match', models.BooleanField(default=False)),
                ('biometric_match', models.BooleanField(default=False)),
                ('webauthn_match', models.BooleanField(default=False)),
                ('biometric_distance', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=10)),
                ('via', models.CharField(default='manual', help_text='manual | live_camera | mobile_pickup | kiosk', max_length=20)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='access_snapshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp'], name='access_acce_timesta_0603e5_idx'), models.Index(fields=['status'], name='access_acce_status_c3f8c9_idx'), models.Index(fields=['event_type'], name='access_acce_event_t_0b085d_idx'), models.Index(fields=['plate_detected'], name='access_acce_plate_d_b3eac4_idx')],
            },
        ),
    ]
