# Generated by Django 5.0.6 on 2026-05-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='0-100 risk score; higher = riskier.')),
                ('band', models.CharField(choices=[('LOW', 'Low (auto grant)'), ('MEDIUM', 'Medium (verify)'), ('HIGH', 'High (deny/escalate)')], max_length=10)),
                ('factors', models.JSONField(default=dict, help_text='Per-input contributions (e.g. {peak: +20, off_hours: +15}).')),
                ('decision_path', models.CharField(blank=True, help_text='Human-readable trace of how the decision was reached.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_event', to='access.accesslog')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp'], name='access_risk_timesta_663656_idx'), models.Index(fields=['band'], name='access_risk_band_898285_idx')],
            },
        ),
    ]
