# Generated by Django 5.0.6 on 2026-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='gate',
            field=models.CharField(blank=True, default='', help_text='Which physical gate/camera caught this event, e.g. ENTRY_CAM, EXIT_CAM, MANUAL_GATE', max_length=20),
        ),
    ]
