# Generated by Django 5.0.6 on 2026-05-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuptoken',
            name='event_type',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], default='EXIT', help_text='Whether this token authorizes ENTRY (arrival) or EXIT (pickup).', max_length=10),
        ),
    ]
